#!/bin/bash

# This client script receives newly-built files from the server script
# and (1) writes them out to the Buffer and (2) feeds them to the chopper.
# When the chopper has run to completion, it touches the file filereceived
# on the Buffer to advance the server.  There is a client log that records
# the output of the Chopper as well as statements when files are complete.
# The client also writes a joblog file for each builder file at
# $RUN.chopper.log to record the job numbers associated to that file.

# This script is designed for use with the L2 Master Script.  It can be run
# independently by giving it the arguments listed below:

# Specifying where to read from
BUILDER=$1
PIPE=$2
DIR=$3
LOG=$4
CHOPPER=$5

# ATTN: This function must be run in a subshell, e.g., in a pipeline
ourtee()
{
trap "" SIGPIPE
exec tee $*
}

trap exit 2

while true
do
# For each file coming from the builder, first receive the filename
# then, receive the file; finally, write list of jobs associated to run

# Receive and parse filename
    FILE=$(ssh $BUILDER cat $PIPE)
    echo $FILE >> $LOG
    RUN=$( echo $FILE | awk 'BEGIN {FS="_"}{print $3}' )
    BIGFILE=$( echo $FILE | awk 'BEGIN {FS="/"}{print $5}' )
    
# Receive file
    ssh $BUILDER cat $PIPE | ourtee -a $DIR/$BIGFILE \
                           | ($CHOPPER -i /dev/stdin -o l2 -r >> $LOG; 
                              ssh $BUILDER touch /Users/snotdaq/server/filereceived ) 

    echo Finished chopping >> $LOG

done
