#! /bin/bash

# This client script receives newly-built files from the Builder and
# (1) copies them to the Buffer and (2) feeds them to the chopper

# Specifying where to read from
BUILDER=snotdaq@snoplusbuilder1.snolab.ca
PIPE=server/pipe

# Specifying where to find database
HOST=snotpenn01
USER=snoplus
PSWD=scintillate

# Save the last job in the last file
OLDJOB=0

# ATTN: This function must be run in a subshell, e.g., in a pipeline
ourtee()
{
trap "" SIGPIPE
exec tee $*
}

trap exit 2

while true
do
# For each file coming from the builder, first receive the filename
# then, receive the file; finally, write list of jobs associated to run

    FILE=$(ssh $BUILDER cat $PIPE)
    RUN=$( echo $FILE | awk 'BEGIN {FS="_"}{print $3}' )

    ssh $BUILDER cat $PIPE | ourtee -a $RUN \
                           | (./chopper -i /dev/stdin -o chopped -c 1 -l 0 -s $HOST -u $USER -p $PSWD; echo true > /mnt/builder/filereceived) 

    echo Finished chopping

    JOB=$( ls -tr closed/chopped* | tail -n 1 | awk 'BEGIN {FS="_"}{print $2}' )
#
#    for ((j=$OLDJOB+1; j<=$JOB; j++))
#    touch $RUN.chopper.log
#    do
#        cat $j >> $RUN.chopper.log
#    done
#
#    OLDRUN=$RUN

done
