#!/bin/bash

# Script to convert ZDAB files to ROOT as they are prepared by Stonehenge
# For use with the L2 Master Script

JOBQUEUE=$1
LOG=$2
MAC=$3
RATENV=$4
SETPGID=$5

source $RATENV

$SETPGID $$

# If we are starting up, refresh the jobqueue
rm $JOBQUEUE
for i in $(ls $MAC)
do
  RUN=$( echo $i | awk 'BEGIN {FS="_"}{print $1}' )
  SUBRUN=$( echo $i | awk 'BEGIN {FS="_"}{print $2}' | 
            awk 'BEGIN {FS="."}{print $1}' )
  NAME=$RUN"_"$SUBRUN".zdab"
  echo ~/bufferscripts/buffer/job $MAC $RUN_$SUBRUN $NAME >> $JOBQUEUE
done

# Check if there is anything to do
while [ "$(cat $JOBQUEUE | wc -l)" -eq 0 ]
do
  echo INFO - No files to process, waiting
  sleep 10
done

# Run the jobs
tail -f -c +1 $JOBQUEUE | parallel -j4 --retries 4 --joblog $LOG
