#!/bin/bash

# This script runs the RAT jobs found in the jobqueue file.
# On start-up, it reconstructs the queue since old jobs are otherwise
# never flushed.  It writes out the stdout output of RAT to batch.log.

DIRLOCAL=$(dirname $0)
LOG=$1
DIR=$2

source ~/rat_env.sh

# First reconstruct the job queue
while [ "$(ls $DIR/*/zdab/* | wc -l)" -eq 0 ]
do
  echo No files to process, waiting!
  sleep 10
done

killall -SIGUSR1 chopper
sleep 1
rm $DIRLOCAL/jobqueue.txt
for i in $(ls $DIR/*/zdab/* | wc -l)
do
  SUBRUN=$(cat $i | awk 'BEGIN {FS="/"}{print $2}' )
  INDEX=$(cat $i | awk 'BEGIN {FS="/"}{print $4}' | \
          awk 'BEGIN {FS="_"}{print $2}' )
  echo ./job $SUBRUN $INDEX $i >> $DIRLOCAL/jobqueue.txt
done
killall -SIGUSR2 chopper

# Then run the jobs
tail -f -c +1 $DIRLOCAL/jobqueue.txt | parallel -j4 --retries 4 --progress \
   >> $LOG

