#! /bin/bash
DATA=~/data_temp
LOG=server.log
FL=served.txt

while true
do
# Get list of files needing serving
    ls -tr $DATA/*.zdab > ls.txt

    while [ $(comm -23 ls.txt $FL | wc -l) -lt 1 ]
        do
            sleep 1
            echo Waiting for data >> $LOG
        done

    FILE=$(comm -23 ls.txt $FL | head -n 1)

# If we have a new file, serve it and the filename to the buffer
    cat > tmp/filename.txt << EOF

$FILE
EOF

    echo Pushing $FILE to pipe >> $LOG
    tail -c +1 tmp/filename.txt > pipe
    tail -f -c +1 $FILE > pipe &
    PID=$(jobs -l | tail -n 1 | awk '{print $2}')
    while [ ! -f filereceived ]
    do
        sleep 1
    done
    rm filereceived
    kill $PID
    echo Reached end of $FILE >> $LOG
    echo $FILE >> $LOG
    echo $FILE >> $FL 

done
