#! /bin/bash
FILE=filereceived
LOG=stopserver.log

while true
do

    if [ -f $FILE ]
        then
            echo File received >> $LOG
            kill $(pgrep tail)
            rm $FILE
        else
            echo waiting >> $LOG
            sleep 1
    fi

done
