#! /bin/bash

DIR=$(dirname $0)
FILE=filereceived
LOG=$DIR/stopserver.log

while true
do

    if [ -f $FILE ]
        then
            echo File received >> $LOG
            kill $(pgrep tail)
            rm $FILE
        else
            echo waiting >> $LOG
            sleep 1
    fi

done
